#coding=utf-8
class PreDefinedData:
	predefinedservice = (
	("name"              ,"protocol","src_port","dst_port","comment" ),
	("ad"                ,"udp"     ,"*"       ,"1773"    ,"udp/1773"),
	("ah"                ,"51"      ,"*"       ,"*"       ,"ah packet (ID of internet protocol:51)"),
	("bgp"               ,"tcp"     ,"*"       ,"179"     ,"tcp/179" ),
	("biff"              ,"udp"     ,"*"       ,"512"     ,"udp/512" ),
	("bootpc"            ,"udp"     ,"*"       ,"68"      ,"udp/68"  ),
	("bootps"            ,"udp"     ,"*"       ,"67"      ,"udp/67"  ),
	("chargen"           ,"tcp"     ,"*"       ,"19"      ,"tcp/19"  ),
	("daytime"           ,"tcp"     ,"*"       ,"13"      ,"tcp/13"  ),
	("diameter"          ,"tcp"     ,"*"       ,"3868"    ,"tcp/3868, sctp/3868"),
	("diameter"          ,"132"    ,"*"       ,"3868"    ,"tcp/3868, sctp/3868"),
	("discard-tcp"       ,"tcp"     ,"*"       ,"9"       ,"tcp/9"   ),
	("discard-udp"       ,"udp"     ,"*"       ,"9"       ,"udp/9"   ),
	("dns"               ,"udp"     ,"*"       ,"53"      ,"udp/53"  ),
	("dns-tcp"           ,"tcp"     ,"*"       ,"53"      ,"tcp/53"  ),
	("dnsix"             ,"udp"     ,"*"       ,"90"      ,"udp/90"  ),
	("echo-tcp"          ,"tcp"     ,"*"       ,"7"       ,"tcp/7"   ),
	("echo-udp"          ,"udp"     ,"*"       ,"7"       ,"udp/7"   ),
	("esp"               ,"50"      ,"*"       ,"*"       ,"esp packet (ID of internet protocol:50)"),
	("exec"              ,"tcp"     ,"*"       ,"512"     ,"tcp/512" ),
	("finger"            ,"tcp"     ,"*"       ,"79"      ,"tcp/79"  ),
	("ftp"               ,"tcp"     ,"*"       ,"21"      ,"tcp/21"  ),
	("gopher"            ,"tcp"     ,"*"       ,"70"      ,"tcp/70"  ),
	("gre"               ,"47"      ,"*"       ,"*"       ,"gre packet (ID of internet protocol:47)"),
	("gtpc"              ,"udp"     ,"*"       ,"2123"    ,"udp/2123 ( gtpv1/gtpv2 )"),
	("gtpu"              ,"udp"     ,"*"       ,"2152"    ,"udp/2152 ( gtpv1 )"),
	("gtpv0"             ,"udp"     ,"*"       ,"3386"    ,"udp/3386"),
	("h225"              ,"tcp"     ,"*"       ,"1720"    ,"tcp/1720"),
	("h323"              ,"tcp"     ,"*"       ,"1719"    ,"tcp/1719"),
	("hostname"          ,"tcp"     ,"*"       ,"101"     ,"tcp/101" ),
	("http"              ,"tcp"     ,"*"       ,"80"      ,"tcp/80"  ),
	("https"             ,"tcp"     ,"*"       ,"443"     ,"tcp/443" ),
	("hwcc"              ,"udp"     ,"*"       ,"10000"   ,"udp/10000"),
	("icmp"              ,"icmp"    ,"*"       ,"*"       ,"icmp protocol (ID of internet protocol:1)"),
	("icmpv6"            ,"58"      ,"*"       ,"*"       ,"icmpv6 protocol (ID of internet protocol:58)"),
	("igmp"              ,"2"       ,"*"       ,"*"       ,"igmp protocol"),
	("ils"               ,"tcp"     ,"*"       ,"1002"    ,"tcp/1002"),
	("imap"              ,"tcp"     ,"*"       ,"143"     ,"tcp/143" ),
	("imaps"             ,"tcp"     ,"*"       ,"993"     ,"tcp/993" ),
	("ipinip"            ,"4"       ,"*"       ,"*"       ,"ipinip protocol"),
	("irc"               ,"tcp"     ,"*"       ,"194"     ,"tcp/194" ),
	("kerberos-tcp"      ,"tcp"     ,"*"       ,"88"      ,"tcp/88"  ),
	("kerberos-udp"      ,"udp"     ,"*"       ,"88"      ,"udp/88"  ),
	("klogin"            ,"tcp"     ,"*"       ,"543"     ,"tcp/543" ),
	("kshell"            ,"tcp"     ,"*"       ,"544"     ,"tcp/544" ),
	("l2tp"              ,"udp"     ,"*"       ,"1701"    ,"udp/1701"),
	("login"             ,"tcp"     ,"*"       ,"513"     ,"tcp/513" ),
	("lpd"               ,"tcp"     ,"*"       ,"515"     ,"tcp/515" ),
	("mgcp"              ,"udp"     ,"*"       ,"2727"    ,"udp/2727"),
	("mms"               ,"tcp"     ,"*"       ,"1755"    ,"tcp/1755"),
	("mobileip-ag"       ,"udp"     ,"*"       ,"434"     ,"udp/434" ),
	("mobileip-mn"       ,"udp"     ,"*"       ,"435"     ,"udp/435" ),
	("msn"               ,"tcp"     ,"*"       ,"1863"    ,"tcp/1863"),
	("msn-audio"         ,"udp"     ,"*"       ,"7001"    ,"udp/7001"),
	("msn-discard"       ,"udp"     ,"*"       ,"9"       ,"udp/9"   ),
	("msn-stun"          ,"udp"     ,"*"       ,"3478"    ,"udp/3478"),
	("mysql"             ,"tcp"     ,"*"       ,"3306"    ,"tcp/3306"),
	("nameserver"        ,"udp"     ,"*"       ,"42"      ,"udp/42"  ),
	("netbios-datagram"  ,"udp"     ,"*"       ,"138"     ,"udp/138" ),
	("netbios-name"      ,"udp"     ,"*"       ,"137"     ,"udp/137" ),
	("netbios-session"   ,"tcp"     ,"*"       ,"139"     ,"tcp/139" ),
	("netbios-ssn"       ,"udp"     ,"*"       ,"139"     ,"udp/139" ),
	("nntp"              ,"tcp"     ,"*"       ,"119"     ,"tcp/119" ),
	("ntp"               ,"udp"     ,"*"       ,"123"     ,"udp/123" ),
	("ospf"              ,"89"      ,"*"       ,"*"       ,"ospf protocol"),
	("pop2"              ,"tcp"     ,"*"       ,"109"     ,"tcp/109" ),
	("pop3"              ,"tcp"     ,"*"       ,"110"     ,"tcp/110" ),
	("pop3s"             ,"tcp"     ,"*"       ,"995"     ,"tcp/995" ),
	("portalserver"      ,"udp"     ,"*"       ,"62314"   ,"udp/62314"),
	("pptp"              ,"tcp"     ,"*"       ,"1723"    ,"tcp/1723"),
	("qq"                ,"udp"     ,"*"       ,"8000"    ,"udp/8000"),
	("radius"            ,"udp"     ,"*"       ,"1812"    ,"udp/1812"),
	("radius-accounting" ,"udp"     ,"*"       ,"1813"    ,"udp/1813"),
	("ras"               ,"udp"     ,"*"       ,"1719"    ,"udp/1719"),
	("rdp-tcp"           ,"tcp"     ,"*"       ,"3389"    ,"tcp/3389"),
	("rdp-udp"           ,"udp"     ,"*"       ,"3389"    ,"udp/3389"),
	("rip"               ,"udp"     ,"*"       ,"520"     ,"udp/520" ),
	("rpc"               ,"tcp"     ,"*"       ,"135"     ,"tcp/135, udp/135"),
	("rpc"               ,"udp"     ,"*"       ,"135"     ,"tcp/135, udp/135"),
	("rsh"               ,"tcp"     ,"*"       ,"514"     ,"tcp/514" ),
	("rtsp"              ,"udp"     ,"*"       ,"554"     ,"udp/554, tcp/554"),
	("rtsp"              ,"tcp"     ,"*"       ,"554"     ,"udp/554, tcp/554"),
	("sccp"              ,"tcp"     ,"*"       ,"2000"    ,"tcp/2000"),
	("sctp"              ,"132"     ,"*"       ,"*"       ,"sctp packet"),
	("sip"               ,"udp"     ,"*"       ,"5060"    ,"udp/5060, tcp/5060"),
	("sip"               ,"tcp"     ,"*"       ,"5060"    ,"udp/5060, tcp/5060"),
	("smb"               ,"tcp"     ,"*"       ,"445"     ,"tcp/445" ),
	("smtp"              ,"tcp"     ,"*"       ,"25"      ,"tcp/25"  ),
	("smtps"             ,"tcp"     ,"*"       ,"465"     ,"tcp/465" ),
	("snmp"              ,"udp"     ,"*"       ,"161"     ,"udp/161" ),
	("snmptrap"          ,"udp"     ,"*"       ,"162"     ,"udp/162" ),
	("sqlnet"            ,"tcp"     ,"*"       ,"1521"    ,"tcp/1521"),
	("sqlserver"         ,"tcp"     ,"*"       ,"1433"    ,"tcp/1433"),
	("ssh"               ,"tcp"     ,"*"       ,"22"      ,"tcp/22"  ),
	("sunrpc-tcp"        ,"tcp"     ,"*"       ,"111"     ,"tcp/111" ),
	("sunrpc-udp"        ,"udp"     ,"*"       ,"111"     ,"udp/111" ),
	("syslog"            ,"udp"     ,"*"       ,"514"     ,"udp/514" ),
	("tacacs"            ,"tcp"     ,"*"       ,"49"      ,"tcp/49"  ),
	("tacacs-ds"         ,"udp"     ,"*"       ,"65"      ,"udp/65"  ),
	("talk-tcp"          ,"tcp"     ,"*"       ,"517"     ,"tcp/517" ),
	("talk-udp"          ,"udp"     ,"*"       ,"517"     ,"udp/517" ),
	("tcp"               ,"tcp"     ,"*"       ,"*"       ,"tcp packet (ID of internet protocol:6)"),
	("telnet"            ,"tcp"     ,"*"       ,"23"      ,"tcp/23"  ),
	("tftp"              ,"udp"     ,"*"       ,"69"      ,"udp/69"  ),
	("time-tcp"          ,"tcp"     ,"*"       ,"37"      ,"tcp/37"  ),
	("time-udp"          ,"udp"     ,"*"       ,"37"      ,"udp/37"  ),
	("udp"               ,"udp"     ,"*"       ,"*"       ,"udp packet (ID of internet protocol:17)"),
	("uucp"              ,"tcp"     ,"*"       ,"540"     ,"tcp/540" ),
	("who"               ,"udp"     ,"*"       ,"513"     ,"udp/513" ),
	("whois"             ,"tcp"     ,"*"       ,"43"      ,"tcp/43"  ),
	("xdmcp"             ,"udp"     ,"*"       ,"177"     ,"udp/177" ),
)

	predefinedicmptype = (
	("ICMP: echo"                       ,"icmp"    ,"8"       ,"0"       ,"Type=8, Code=0"),
	("ICMP: echo-reply"                 ,"icmp"    ,"0"       ,"0"       ,"Type=0, Code=0"),
	("ICMP: fragmentneed-DFset"         ,"icmp"    ,"3"       ,"4"       ,"Type=3, Code=4"),
	("ICMP: host-redirect"              ,"icmp"    ,"5"       ,"1"       ,"Type=5, Code=1"),
	("ICMP: host-tos-redirect"          ,"icmp"    ,"5"       ,"3"       ,"Type=5, Code=3"),
	("ICMP: host-unreachable"           ,"icmp"    ,"3"       ,"1"       ,"Type=3, Code=1"),
	("ICMP: information-reply"          ,"icmp"    ,"16"      ,"0"       ,"Type=16, Code=0"),
	("ICMP: information-request"        ,"icmp"    ,"15"      ,"0"       ,"Type=15, Code=0"),
	("ICMP: net-redirect"               ,"icmp"    ,"5"       ,"0"       ,"Type=5, Code=0"),
	("ICMP: net-tos-redirect"           ,"icmp"    ,"5"       ,"2"       ,"Type=5, Code=2"),
	("ICMP: net-unreachable"            ,"icmp"    ,"3"       ,"0"       ,"Type=3, Code=0"),
	("ICMP: parameter-problem"          ,"icmp"    ,"12"      ,"0"       ,"Type=12, Code=0"),
	("ICMP: port-unreachable"           ,"icmp"    ,"3"       ,"3"       ,"Type=3, Code=3"),
	("ICMP: protocol-unreachable"       ,"icmp"    ,"3"       ,"2"       ,"Type=3, Code=2"),
	("ICMP: reassembly-timeout"         ,"icmp"    ,"11"      ,"1"       ,"Type=11, Code=1"),
	("ICMP: source-quench"              ,"icmp"    ,"4"       ,"0"       ,"Type=4, Code=0"),
	("ICMP: source-route-failed"        ,"icmp"    ,"3"       ,"5"       ,"Type=3, Code=5"),
	("ICMP: timestamp-reply"            ,"icmp"    ,"14"      ,"0"       ,"Type=14, Code=0"),
	("ICMP: timestamp-request"          ,"icmp"    ,"13"      ,"0"       ,"Type=13, Code=0"),
	("ICMP: ttl-exceeded"               ,"icmp"    ,"11"      ,"0"       ,"Type=11, Code=0"),
)

	predefinedicmpv6type = (
	("ICMPv6: Redirect"                 ,"58"      ,"137"     ,"0"       ,"Type=137, Code=0"),
	("ICMPv6: echo"                     ,"58"      ,"128"     ,"0"       ,"Type=128, Code=0"),
	("ICMPv6: echo-reply"               ,"58"      ,"129"     ,"0"       ,"Type=129, Code=0"),
	("ICMPv6: err-Header-field"         ,"58"      ,"4"       ,"0"       ,"Type=4, Code=0"),
	("ICMPv6: frag-time-exceeded"       ,"58"      ,"3"       ,"1"       ,"Type=3, Code=1"),
	("ICMPv6: hop-limit-exceeded"       ,"58"      ,"3"       ,"0"       ,"Type=3, Code=0"),
	("ICMPv6: host-admin-prohib"        ,"58"      ,"1"       ,"1"       ,"Type=1, Code=1"),
	("ICMPv6: host-unreachable"         ,"58"      ,"1"       ,"3"       ,"Type=1, Code=3"),
	("ICMPv6: neighbor-advertisement"   ,"58"      ,"136"     ,"0"       ,"Type=136, Code=0"),
	("ICMPv6: neighbor-solicitation"    ,"58"      ,"135"     ,"0"       ,"Type=135, Code=0"),
	("ICMPv6: network-unreachable"      ,"58"      ,"1"       ,"0"       ,"Type=1, Code=0"),
	("ICMPv6: packet-too-big"           ,"58"      ,"2"       ,"0"       ,"Type=2, Code=0"),
	("ICMPv6: port-unreachable"         ,"58"      ,"1"       ,"4"       ,"Type=1, Code=4"),
	("ICMPv6: router-advertisement"     ,"58"      ,"134"     ,"0"       ,"Type=134, Code=0"),
	("ICMPv6: router-solicitation"      ,"58"      ,"133"     ,"0"       ,"Type=133, Code=0"),
	("ICMPv6: unknown-ipv6-opt"         ,"58"      ,"4"       ,"2"       ,"Type=4, Code=2"),
	("ICMPv6: unknown-next-hdr"         ,"58"      ,"4"       ,"1"       ,"Type=4, Code=1"),
)